# -*- coding: utf-8 -*-

"""
/***************************************************************************
 UAVPreparerProcessing
                                 A QGIS plugin
 This plugin examines height properties on a DSM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-06
        copyright            : (C) 2021 by Oskar Bäcklin University of Gothenburg
        email                : oskar.backlin@gu.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Oskar Bäcklin University of Gothenburg'
__date__ = '2021-05-06'
__copyright__ = '(C) 2021 by Oskar Bäcklin University of Gothenburg'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsFeatureSink,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterField,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterFeatureSink
                       )
#from qgis.analysis import QgsZonalStatistics
from qgis.analysis import QgsZonalStatistics

import os
import numpy as np
from osgeo import gdal
import pandas as pd
import geopandas as gpd

class UAVPreparerProcessingAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT_DSM = 'INPUT_DSM'
    INPUT_POINT = 'INPUT_POINT'
    ID_FIELD = 'ID_FIELD'
    RADIUS = 'RADIUS'
    OUTPUT_FILE = 'OUTPUT_FILE'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.plugin_dir = os.path.dirname(__file__)

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT_POINT,
                self.tr('Input Point Layer'),
                [QgsProcessing.TypeVectorPoint]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterField(
                self.ID_FIELD,
                self.tr('ID field'),
                '',
                self.INPUT_POINT,
                QgsProcessingParameterField.Numeric
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_DSM,
                self.tr('Digital Surface Model')
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.RADIUS,
                self.tr('Radius (m)'),
                QgsProcessingParameterNumber.Double,
                100,
                False
            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_FILE,
                self.tr('Output file with tabular metric information'),
                self.tr('TXT files (*.txt)')
            )
        )


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        # Input parameters
        vlayer = self.parameterAsVectorLayer(parameters, self.INPUT_POINT, context)
        idField = self.parameterAsFields(parameters, self.ID_FIELD, context)
        dsm_layer = self.parameterAsRasterLayer(parameters, self.INPUT_DSM, context)
        r = self.parameterAsDouble(parameters, self.RADIUS, context)
        outputFile = self.parameterAsFileOutput(parameters, self.OUTPUT_FILE, context)

        provider = dsm_layer.dataProvider()
        filepath_dsm = str(provider.dataSourceUri())
        idx = vlayer.fields().indexFromName(idField[0])
        numfeat = vlayer.featureCount()
        result = np.zeros([numfeat, 4])

        for f in vlayer.getFeatures():

            if feedback.isCanceled():
                break

            i = 0
            feedback.setProgress(int((i * 100) / numfeat))
            # get coordinates from the point
            y = f.geometry().centroid().asPoint().y()
            x = f.geometry().centroid().asPoint().x()

            bbox  = (x - r, y + r, x + r, y - r)
            bigraster = gdal.Open(filepath_dsm)
            gdal.Translate(self.plugin_dir + '/clipdsm.tif', bigraster, projWin = bbox)
            bigraster = None
            data = gdal.Open(self.plugin_dir + '/clipdsm.tif')
            mat = np.array(data.ReadAsArray()).astype(float)

            result[i, 0] = int(f.attributes()[idx])
            result[i, 1] = np.mean(mat)
            result[i, 2] = np.max(mat)
            result[i, 3] = np.min(mat)

            i = i + 1

        # Saving to file
        numformat = '%d ' + '%6.2f ' * 3
        headertext = 'id mean max min'
        np.savetxt(outputFile, result, fmt = numformat, delimiter = ' ', header = headertext)  
        feedback.setProgressText('UAV Preparer. Operation successful!')
        return {self.OUTPUT_FILE: outputFile}

#        self.iface.messageBar().pushMessage('UAV Preparer. Operation successful!', level = Qgis.Success, duration =5 )

#         # Inputs
#         drones = gpd.read_file(vlayer)

#         # Set radius and syle for buffer 
#         style = 3 # 1 circle 3 square
# #        radius = 100.

#         # Buffer point
#         drones['buff'] = drones['geometry'].buffer(r, cap_style = 3)

#         # Calculate mean min max count (zonal statistics using the created buffer")
#         drones_zonal_stats = drones.join(pd.DataFrame(zonal_stats(drones['buff'],dsm)))

#         # Print to txt file for columns: mean, min , max with tab-seperator
#         drones_zonal_stats.set_index('id')[['mean','min','max']].to_csv('droneheight_gpd_rasterio.txt', sep = '\t')



        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'UAV Preparer for Processing'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return UAVPreparerProcessingAlgorithm()
